### ISSUE TITLE
Check subscriptions for nulls

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#33]
Add directives?

**Comment by ddgenome** [comment]
`@required`

**Comment by johnsonr** [comment]
Deferred as not causing immediate problems. When `@required` is added it makes subscriptions impossible to test in GraphiQL because they time out. @slimslenderslacks @whostolebenfrog any thoughts on this?

**Comment by slenderslack** [comment]
@required is just a post-neo filter right now (it _SHOULD_ be an additional constraint sent to neo but that's not what's happening today).  It's likely that the timeout you're seeing is because the underlying query (without the @required directives) times out.  

And quite often, the query that you're running is unbound at the root node because you're testing a subscription?  Is that the case here?
