### ISSUE TITLE
Add more Configuration Validation types

### ISSUE THREAD

**Issue by ipcrm** [atomist/sdm#580]
Currently validateConfigurationValues supports string, number, and boolean.  However, there are use cases where the config value itself will be an object or an array.  It would be good if we could add `any` to simply confirm that an element exists, and to add an `array` type to validate arrays.

**Comment by johnsonr** [comment]
Could we also allow optional configuration values to be specified? Why is it only "required"?

**Comment by cdupuis** [comment]
Yeah, the whole configuration area will get some more features soon. I'm planning on adding more metadata so that we can ask the user to specify the configuration when they are missing during SDM startup. Obviously only when running in non-production mode. 

Adding validation for optional values is certainly possible and I make a note of that.
