### ISSUE TITLE
Errors code transforms disappear. Print them to the log please

### ISSUE THREAD

**Issue by cdupuis** [atomist/sdm#746]
Issue moved from atomist/sdm-core#164

Created by @jessitron at 2019-06-06T19:09:06Z:

When a code transform throws an exception or returns failure, this is ignored and the goal completes successfully.

This is okay, but I want to see the exception or the error property of the TransformResult. Please print this to the log.

**Comment by cdupuis** [comment]
@jessitron is that really not coming out in either the progressLog or the SDM log? See https://github.com/atomist/sdm/blob/master/lib/api-helper/listener/executeAutofixes.ts#L258-L269

**Comment by jessitron** [comment]
All I see in my progressLog is 
`Edited https://github.com/satellite-of-love/docs with autofix code inline and success=false, edited=NaN`

(this is returning failure, rather than throwing an exception)

You probably have access to satellite-of-love, so: https://app.atomist.com/workspace/T1JVCMVH7/logs/satellite-of-love/docs/ada334fb976d9d09d825c15f4ca7235ccd6ad98a/0-code/autofix%23machine.ts%3A87/a9c3a8ff-b2d4-40c2-bd81-e1c8a62a16f0/4004d4d5-de28-4bb6-8e33-21940f12463f

I explicitly set `ignoreFailure` to false, and still, no exception shows up.
