### ISSUE TITLE
Review wording of contexts and messages 

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm#77]

**Comment by WillGardella** [comment]
Hi Jess, sorry this took me so long to get back to you, hopefully you can still tweak this.

Suggestions:

1. Hide fingerprints line for now, it's just confusing and it raises the question what the difference is between that and scan (at least, once you explain what scan means))
2. Your "Phases" attachment shows information that's duplicated elsewhere
2.1 *Build* also shows up to the right of the SHA bf2db13
2.2 *Deploy failure* also shows up in the next message at 1:39PM
2.3 The *services* attachment is showing a service started in `development` and you show find and verify endpoint in `Test`. Maybe these are different types of services, not sure, but it's hard to understand what's going on
2.4 The release button under `Tag` is confusing. Isn't the example being deployed to production? 
3. Group the messages in Phases into three Slack attachments
- Title: Scans, then put your `scan` here. I don't think you need to show `build` and `find artifact` at all but I could be not understanding the scenario
- Title: Test. Then, on a single line `Listening for artifacts` --> `Deploying to Test` --> `Discovering endpoint` --> `Verifying endpoint` --> `Running`
- Title: Production. with the same thing as Test

If you want to pre-fab all the stages so that they can see them and then overwrite the message as progress is made, you could do something like
`Listening for artifacts` --> `Deploy` --> `Discover Endpoint` --> `Verify Endpoint` and then change the words 

You could do something with the icons to support those (we generally have the flashing icon for pending jobs, but we usually use that only when we kick off something.

Hopefully this makes sense, it's a lot of text. Happy to zoom.

**Comment by jessitron** [comment]
@cdupuis , where does the fingerprints status come from? Is it in Lifecycle? Can we remove it? (see #1)

**Comment by johnsonr** [comment]
Currently there's a Maven dependencies fingerprint calculated. We can easily disable that. However, because fingerprints are used to trigger a deployment stage (which @slimslenderslacks recommended) lifecycle will still render the fingerprints line in any case. So I'd be inclined to keep it. If people notice, we can explain it. The difference between fingerprints and scan is _semantic diff_ vs _analyze the latest state of the code_.

I'd prefer not to monkey with lifecycle at this point just for this.

**Comment by johnsonr** [comment]
@WillGardella thanks for the review. I like your suggested wording.

Suppressing some of those phases may not be easy, as they are GitHub statuses, which are displayed by default. I guess we could use some marker that lifecycle recognized to say they should be hidden. That would a useful change for lifecycle in general.

**Comment by jessitron** [comment]
I'm in favor of showing the fingerprints line (but NOT using them to trigger a deployment phase; that's no semantic diff; Clay is working on using a Phase instead)
... but also of hiding the "no blocking fingerprints" status -- that's a feature we can add later, after we have a good story and docs for how to use it. We have a lot of catching up to do on the docs before we get to that

**Comment by ddgenome** [comment]
You can probably disable fingerprint rendering by running config lifecycle

**Comment by johnsonr** [comment]
Yes, the "blocking fingerprint" status doesn't make sense to me
